# Background and foreground colors
background = #150D08
foreground = #F6F0CF

# Standard colors
palette = 0=#150D08
palette = 1=#d75423
palette = 2=#F4E3A6
palette = 3=#F7ECB9
palette = 4=#8dacf7
palette = 5=#d593d5
palette = 6=#2fc5c5
palette = 7=#F6F0CF

# Bright colors
palette = 8=#6d6763
palette = 9=#ff7536
palette = 10=#f7e697
palette = 11=#f1e7a6
palette = 12=#abcaff
palette = 13=#fcaeff
palette = 14=#45e9e9
palette = 15=#ece6bd
