background            #150D08
foreground            #F6F0CF

# black
color0  #150D08
color8  #6d6763

# red
color1  #d75423
color9  #ff7536

# green
color2  #F4E3A6
color10 #f7e697

# yellow
color3  #F7ECB9
color11 #f1e7a6

# blue
color4  #8dacf7
color12 #abcaff

# magenta
color5  #d593d5
color13 #fcaeff

#cyan
color6  #2fc5c5
color14 #45e9e9

#white
color7  #F6F0CF
color15 #ece6bd


